spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb  # MySQL 서버 URL 및 데이터베이스
    username: user                         # MySQL 사용자
    password: user                # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: admin  # Redis 비밀번호 설정
      timeout: 6000    # 연결 타임아웃 (밀리초)
      lettuce:
        pool:
          max-active: 10  # 최대 활성 커넥션 수
          max-idle: 5     # 최대 유휴 커넥션 수
          min-idle: 1     # 최소 유휴 커넥션 수
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
