spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb  # MySQL 서버 URL 및 데이터베이스
    username: user                         # MySQL 사용자
    password: user                # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: admin  # Redis 비밀번호 설정
      timeout: 6000    # 연결 타임아웃 (밀리초)
      lettuce:
        pool:
          max-active: 10  # 최대 활성 커넥션 수
          max-idle: 5     # 최대 유휴 커넥션 수
          min-idle: 1     # 최소 유휴 커넥션 수
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# swagger 설정
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  api-docs:
    enabled: true
    path: '/docs'
  swagger-ui:
    enabled: true
    path: '/swagger'
    try-it-out-enabled: true
    operations-sorter: alpha
  
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static-region: ${S3_REGION}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

jwt:
  secret-key: ${SECRET_KEY}
  access-token-exp: ${ACCESS_TOKEN_EXP}
  refresh-token-exp: ${REFRESH_TOKEN_EXP}